<?php
$s="#GENERATED BY make.php AT ".date("Y-m-d H:i:s").".\n#@author:Liu Guangfeng\n#@email:email@liuguangfeng.cn\n\nNameVirtualHost *:80\n";
$dir=opendir(".");
$i=0;
$owners=array();
while(($owner=readdir($dir))!==false){
  if(is_dir($owner)&&$owner!="."&&$owner!=".."&&$owner!="xampp"&&$owner!="webalizer"){
    $owners[]=$owner;
  }
}
unset($owner);
sort($owners);
foreach($owners as $owner){
    //so i go to your dir.
    $yourdir=opendir($owner);
    $s.="\n########for {$owner}\n";
    while(($site=readdir($yourdir))!==false){
      if(is_dir($owner."/".$site)&&$site!="."&&$site!=".."){
        $i++;$realpath=realpath(".") ."/{$owner}/{$site}";
        $s.=<<<EOF
<VirtualHost *:80>
    ServerAdmin admin@{$site}
    DocumentRoot "{$realpath}"
    ServerName {$site}
    ServerAlias www.{$site}
    ErrorLog "logs/{$site}-error.log"
    CustomLog "logs/{$site}-access.log" combined
</VirtualHost>

EOF;
      }
    }
}

file_put_contents("/opt/lampp/etc/extra/httpd-vhosts.conf",$s);
echo "i found {$i} sites in total\n开始重启apche。。。\n";
exec("/opt/lampp/lampp restartapache",$out);
foreach($out as $v)echo $v."\n";
?>